SELECT (
   ROUND(5.7)
   ROUND(5.789,2) =MEANS ROUNDING AFTER TWO DECIMAL DIGITS
   TRUNCATE(5.789,2)= MEANS REMOVE TWO DIGITS AFTER THE DECIMAL POINT
   CEILING(5.23)=THE SMALLEST INTERGER THAT IS  THAN OR EQUAL TO THIS NUMBER->6
   FLOOR(5.23) ==THE LARGEST INTERGER THAT IS LESS THAN OR EQUAL TO THIS NUMBER->6
   RAND()=GETTING THE RANDOM NUMBER
   ABS(-7.6)=RETURNING POSITIVE ABSOLUTE VALUE