 SELECT (
   substring('KINDERGARTEN',3,5) ->RETURNING SUBSTRING OF STRING
   length('KINDERGARTEN') -> LENGHT OF STRING
   UPPER('KINDERGARTEN') -> CONVERTING STRING TO UPPER CASE
   CONCAT('KINDERGARTEN',' ' ,'THERE') -> CONCATINATING STRING
   LOCATE('DER','KINDERGARTEN')
   REPLACE('KINDERGARTEN','GARTEN','GARDEN')
   RIGHT('KINDERGARTEN',4) ->GET FOUR CHARACTERS FROM RIGHT OR LEFT