SELECT  date_add(now(),interval 1 year)::-> ADDING ONE YEAR,MONTH,DAY TO THE CURRENT DAY TIME
SELECT  date_SUB(now(),interval 1 year)::->SUBTRACTING ONE YEAR,MONTH,DAY TO THE CURRENT DAY TIME
SELECT  datediff('2025-07-07','2025-01-01') AS DAYS_DIFFRENT::->GETTING DIFFRENT IN DAYS
SELECT  timediff('09:00','09:02')::->DIFFRENCE IN DAYS
SELECT  time_to_sec('09:00')-time_to_sec('09:02') ::-> DIFFRENCE IN TIMES
SELECT  time_to_sec('09:00')::TIMES ELAPSED SINCE  MIDNIGHT
