SELECT 
   now() ->CURRENT DATE AND TIME
   current_date()->CURRENT DATE ONLY
    current_timestamp()->CURRENT TIME
   dayname (now()) -> GETTING THE NAME OF THE DAY FROM NOW
   EXTRACT(WEEK FROM NOW())::->FROM NOW() WE ARE GETTING A WEEK,YEAR,MONTH ,DAY OR EVEN AN HOUR